spring:
  application:
    name: gateway
  config:
    import: 'optional:configserver:http://localhost:8888'
  cloud:
    config:
      uri: http://config-server:8888/
        #discovery:
        #serviceId: config-server
      #enabled: true
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            #allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Origin
              - X-Requested-With
              - Content-Type
              - Accept
              - Authorization
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: users-service
          uri: lb://USERS-SERVICE
          #uri: lb://users-service
          predicates:
            - Path=/user/**
        - id: accounts-service
          uri:  lb://ACCOUNTS-SERVICE
          #uri: lb://accounts-service
          predicates:
            - Path=/account/**
      discovery:
        locator:
          enabled: true # Habilitar descubrimiento de servicios
          lower-case-service-id: true   # Convertir IDs de servicio a minúsculas
management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true
info:
  app:
    name: Gateway
    description: API gateway
    version: 1.0.0

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: http://localhost:8084/actuator/info
    healthCheckUrlPath: http://localhost:8084/actuator/info
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8084
